### ISSUE TITLE
Message gets deleted when using a service that does "previews"

### ISSUE THREAD

**Issue by michaelavila** [thingssimple/burnbox#5]
If I use slack to send a burn box link, the message will be deleted before the receiver has the chance to click on it.

**Comment by brianriley** [comment]
I watched Slack do this. It runs a fairly standard GET request on the URL. Aside from maintaining a running list of user agents to block from GETting a message URL, I'm not sure how best to handle this. Thoughts?

**Comment by brianriley** [comment]
I pushed a fix up for Slackbot for now. We'll have to add other user agents as we discover them.
